version: '3.8'

services:
  backend:
    build: ./backend-node
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3000

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL_NODE=http://localhost:3000/api
